export const caseListData = {
    getCaseListData() {
        return {
            list: [
                {
                    "id": 15651,
                    "patient_sex": "男",
                    "patient_age": 123,
                    "expert_name": null,
                    "top_face_image": "",
                    "patient_name": "test",
                    "case_no": "24071129",
                    "createtime": 1720681489,
                    "updatetime": 0,
                    "name": "sharon",
                    "case_status": 0,
                    "model_status": 0,
                    "plan_status": 3,
                    "plan_up_status": 0,
                    "make_status": 1,
                    "exp_status": 0,
                    "status": 0,
                    "user_id": 3190,
                    "doctor": "Sharon",
                    "is_e": 0,
                    "is_close": 0,
                    "clinical": "{\"guxing\":\"\\u672a\\u77e5\",\"gaodi\":\"\\u672a\\u77e5\",\"anshi\":\"\\u672a\\u77e5\"}",
                    "fixed_slot": "",
                    "apply_end": "0",
                    "case_color": -1,
                    "model_color": -1,
                    "plan_color": -1,
                    "make_color": -1,
                    "exp_color": -1,
                    "difficulty": 0
                },
                {
                    "id": 15285,
                    "patient_sex": "女",
                    "patient_age": 10,
                    "expert_name": null,
                    "top_face_image": "https://alphacdn.protectmec.com/uploads/2024/07/3c59d20240702133218542987.jpg",
                    "patient_name": "bella Zhang",
                    "case_no": "24070252",
                    "createtime": 1719898090,
                    "updatetime": 1720858851,
                    "name": "sharon",
                    "case_status": 1,
                    "model_status": 1,
                    "plan_status": 2,
                    "plan_up_status": 0,
                    "make_status": 4,
                    "exp_status": 1,
                    "status": 5,
                    "user_id": 3190,
                    "doctor": "Sharon",
                    "is_e": 0,
                    "is_close": 0,
                    "clinical": "{\"guxing\":\"\\u9aa8\\u6027\\u4e00\\u7c7b\",\"gaodi\":\"\\u672a\\u77e5\",\"anshi\":\"\\u5b89\\u6c0f\\u4e00\\u7c7b\"}",
                    "fixed_slot": "普特 PT MAX 自锁 - MBT",
                    "apply_end": "0",
                    "case_color": -3,
                    "model_color": -3,
                    "plan_color": -3,
                    "make_color": -3,
                    "exp_color": -2,
                    "difficulty": 0
                },
                {
                    "id": 15225,
                    "patient_sex": "女",
                    "patient_age": 12,
                    "expert_name": null,
                    "top_face_image": "https://alphacdn.protectmec.com/uploads/2024/07/c7e1220240701112203129918.jpg",
                    "patient_name": "yuyi zhang",
                    "case_no": "24070139",
                    "createtime": 1719804002,
                    "updatetime": 1720858862,
                    "name": "sharon",
                    "case_status": 1,
                    "model_status": 1,
                    "plan_status": 2,
                    "plan_up_status": 0,
                    "make_status": 4,
                    "exp_status": 1,
                    "status": 5,
                    "user_id": 3190,
                    "doctor": "Sharon",
                    "is_e": 0,
                    "is_close": 0,
                    "clinical": "{\"guxing\":\"\\u9aa8\\u6027\\u4e00\\u7c7b\",\"gaodi\":\"\\u5747\\u89d2\",\"anshi\":\"\\u5b89\\u6c0f\\u4e8c\\u7c7b\",\"other\":[]}",
                    "fixed_slot": "普特 PT MAX 自锁 - 中转矩",
                    "apply_end": "0",
                    "case_color": -3,
                    "model_color": -3,
                    "plan_color": -3,
                    "make_color": -3,
                    "exp_color": -2,
                    "difficulty": 0
                }
            ],
            count: 3,
            next_page: 0
        }

    },

    getPatients() {
        return Promise.resolve(this.getCaseListData());
    },
}